import { mkdir, writeFile, readFile } from "node:fs/promises";
import path from "node:path";

export const WORKFLOW_PATH = ".github/workflows/installguard.yml";

/**
 * Emit the workflow most people would otherwise never get around to writing.
 *
 * Ordering is the point: `preflight` runs before any install, so a poisoned
 * lockfile is caught while nothing has executed on the runner. Only then does
 * the job install with scripts disabled and diff against the baseline.
 */
export function renderWorkflow({ nodeVersion = "20", sarif = true } = {}) {
  const upload = sarif
    ? `
      - name: Upload results to the Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: installguard.sarif
`
    : "";
  return `# Generated by \`installguard ci --init\`
name: installguard

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 6 * * 1"

permissions:
  contents: read
  security-events: write

jobs:
  install-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "${nodeVersion}"

      # Runs against the lockfile only — nothing has been installed yet.
      - name: Preflight (before anything executes)
        run: npx --yes installguard preflight --ci

      - name: Install without running scripts
        run: npm ci --ignore-scripts

      - name: Fail on new or modified install scripts
        run: npx --yes installguard diff --ci

      - name: Flag releases published in the last 3 days
        run: npx --yes installguard cooldown --days 3 --ci
        continue-on-error: true

      - name: Report findings as SARIF
        if: always()
        run: npx --yes installguard scan --sarif > installguard.sarif
${upload}`;
}

export async function writeWorkflow(projectDir, options = {}) {
  const target = path.join(projectDir, WORKFLOW_PATH);
  try {
    await readFile(target, "utf8");
    if (!options.force) return { target, written: false, reason: "exists" };
  } catch {
    /* not there yet — good */
  }
  await mkdir(path.dirname(target), { recursive: true });
  await writeFile(target, renderWorkflow(options), "utf8");
  return { target, written: true };
}
